// ******************* FILE INFO *******************
// File Name: firebase_options.dart
// Description: Firebase configuration (auto-generated)
// Created by: Amr Mesbah
// Last Update: 31/05/2026

/// Module: app

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45C8OKpo7lW_ikQJQbg7eDxtPyUzVLIY',
    appId: '1:1008435332908:web:2b847bb674d0bc5cbbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    authDomain: 'beauty-user.firebaseapp.com',
    storageBucket: 'beauty-user.firebasestorage.app',
    measurementId: 'G-VLNWGDCBCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA717oQJvOAioo9KAStmwWWvKOT9RoOGsk',
    appId: '1:1008435332908:android:23c9a9ecfb729ec6bbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    storageBucket: 'beauty-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4S3bPo_GqwoCrJ81I1BLKtMU5eP6sVWE',
    appId: '1:1008435332908:ios:9437e4ead15758b9bbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    storageBucket: 'beauty-user.firebasestorage.app',
    iosBundleId: 'com.beautyadmin.bayanatz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4S3bPo_GqwoCrJ81I1BLKtMU5eP6sVWE',
    appId: '1:1008435332908:ios:da97a6df61ce1207bbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    storageBucket: 'beauty-user.firebasestorage.app',
    iosBundleId: 'com.example.beautyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA45C8OKpo7lW_ikQJQbg7eDxtPyUzVLIY',
    appId: '1:1008435332908:web:9bbdbb2a088027e1bbce89',
    messagingSenderId: '1008435332908',
    projectId: 'beauty-user',
    authDomain: 'beauty-user.firebaseapp.com',
    storageBucket: 'beauty-user.firebasestorage.app',
    measurementId: 'G-EJZHTXZRBT',
  );
}
